### PR TITLE
Create vlmcsd.service

### PR DESCRIPTION
**Pull request by wupz-repo**
CentOS 7  systemctl service controller files

### CODE REVIEW

**Comment by simonsmh** [comment]
https://github.com/Wind4/vlmcsd-debian/blob/master/vlmcsd.service

**Comment by cnwpz** [comment]
this CentOS 7 systemctl service controller files,It's not consistent with debian service file;

**Comment by cnwpz** [comment]
The vlmcsd.service file is added to complete the build of the RPM package with vlmcsd.spec and under CentOS;

**Comment by rouben** [comment]
Maybe we need a separate submodule for RPM package building?

**Pull request closed without merging**
