### PR TITLE
Add debian/ dir for deb packaging

### PR DESCRIPTION
**Pull request by simonsmh**

### CODE REVIEW

**Comment by ChlorideCull** [comment]
Since this repo is a mirror, I'm not entirely sure pull requests are accepted, but some feedback:

I see that the manpages have been regenerated, I personally don't believe this to be necessary as the only change is in the "created" metadata comments. The issue is that git doesn't efficiently handle binary files, so each update to them will essentially create a duplicate in the history, rapidly bloating the size of the repository.

You'll need to amend and rebase to remove the change, I'm not sure if you've done that before, but I'm sure there's a guide somewhere.

**Comment by simonsmh** [comment]
That's a lot better now. LOL

**Comment by rouben** [comment]
Pull request 4 was accepted (it was a trivial documentation change).

If this is a mirror, where’s the original? I tried following the mydigitallife forum link in the project description, but it requires me to register which I am not terribly keen to do...

**Comment by ChlorideCull** [comment]
The original is on MDL, in that thread. Development is done on Hotbird64's private SVN server, apparently, they just upload a 7z with the source and binaries whenever they release a new version, development itself isn't public.

Your pull request was accepted because the Github page is obviously not maintained there, but here.

**Comment by simonsmh** [comment]
Never mind~~ If this pr helps any people, that's enough :)

**Comment by rouben** [comment]
@ChlorideCull did not know that! Thanks for clarifying.

@Wind4 am I correct to presume that this project then as an "unofficial" package repo for new releases? Building RPMs and DEBs for the community to use would be very useful, IMHO. So the question is, how are you moving the code here? Are you manually grabbing the source code off MDL and applying commits to this repo, and uploading the binaries to the Releases page? Or, do you have access to the SVN repo and set up a sync of some sort (e.g. using [Subgit](https://subgit.com/) or similar tool)?

It'd be nice to be able to offer an actual package repo... A PPA for Ubuntu users, and/or perhaps [OpenSUSE Build](https://build.opensuse.org/) for other distros (not just SuSE)?

**Comment by Wind4** [comment]
I'm not the owner of vlmcsd.
But I think we can use git submodule to improve it.

**Comment by simonsmh** [comment]
Do whatever you want to do, the code has already there @Wind4 :)

**Comment by rouben** [comment]
This has been implemented in commit 28a50f7.

**Pull request closed without merging**
